# Numpy Fast Tutorial
[numpy.org](http://www.numpy.org/)

In [1]:
import numpy as np

In [2]:
l = [
    [1, 2, 3],
    [4, 5, 6],
]

print(type(l))
l

<class 'list'>


[[1, 2, 3], [4, 5, 6]]

In [3]:
a = np.array(l)

print(type(a))
a

<class 'numpy.ndarray'>


array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a.shape

(2, 3)

In [5]:
# all the same
print(a.size)
print(np.prod(a.shape))

6
6


In [6]:
# all the same
print(a.ndim)
print(len(a.shape))

2
2


## Slice, indexování

In [22]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [8]:
print(a[0, 1])
print(type(a[0, 1]))

2
<class 'numpy.int64'>


In [9]:
print(a[0, :])
print(a[:, 1])

[1 2 3]
[2 5]


In [10]:
# all the same
print(a[0, 1:3])
print(a[0, 1:])
print(a[0, 1:1000])  # No exception
print(a[0, 1:None])  
print(a[[0], [1, 2]])
print(a[[True, False], [False, True, True]])


[2 3]
[2 3]
[2 3]
[2 3]
[2 3]
[2 3]


In [11]:
print(a[0, 0:-1])

[1 2]


Indexování boolean polem stejného shapu

In [12]:
mask = (a > 3) & (a < 6)  # () neccessary
print(mask)
a[mask]

[[False False False]
 [ True  True False]]


array([4, 5])

## Slice step

In [13]:
a = list(range(5))
a

[0, 1, 2, 3, 4]

In [14]:
a[::2]

[0, 2, 4]

In [15]:
a[::-1]

[4, 3, 2, 1, 0]

In [16]:
a[4:1:-1]

[4, 3, 2]

## Transformace

In [23]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [24]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [26]:
print(a.T)

[[1 4]
 [2 5]
 [3 6]]


In [27]:
# all the same
print(a[:, :, np.newaxis].shape)
print(a[:, :, None].shape)
print(a[..., np.newaxis].shape)
print(a.reshape(2, 3, 1).shape)

(2, 3, 1)
(2, 3, 1)
(2, 3, 1)
(2, 3, 1)


## dtype

In [28]:
a.dtype

dtype('int64')

In [29]:
a.astype(np.float32)

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

# Stack
The arrays must have the same shape, except in the dimension corresponding to axis (the first, by default).

## Přidat řádek

In [30]:
print(a)
b = np.array([7, 8, 9])
print(b)

[[1 2 3]
 [4 5 6]]
[7 8 9]


In [31]:
b = np.array([7, 8, 9])
b = b[np.newaxis, :] 

print(a, a.shape)
print(b, b.shape)
print()

# all the same
print(np.vstack([a, b]))
print(np.concatenate([a, b], axis=0))

[[1 2 3]
 [4 5 6]] (2, 3)
[[7 8 9]] (1, 3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Přidat sloupec

In [32]:
print(a)
c = np.array([3.5, 6.5])
print(c)

[[1 2 3]
 [4 5 6]]
[3.5 6.5]


In [33]:
c = c[:, np.newaxis] 

print(a, a.shape)
print(c, c.shape)
print()

# all the same
print(np.hstack([a, c]))
print(np.concatenate([a, c], axis=1))

[[1 2 3]
 [4 5 6]] (2, 3)
[[3.5]
 [6.5]] (2, 1)

[[1.  2.  3.  3.5]
 [4.  5.  6.  6.5]]
[[1.  2.  3.  3.5]
 [4.  5.  6.  6.5]]


# Matrix multiplication

In [34]:
x = np.eye(2) * 2 # jednotková matice vynásobená 2 (elementwise)
print(x)
print(a)
print()

[[2. 0.]
 [0. 2.]]
[[1 2 3]
 [4 5 6]]



In [35]:
# all the same
print(x @ a)  # The matmul function implements the semantics of the @ operator introduced in Python 3.5 following PEP465.
print(np.matmul(x, a))

[[ 2.  4.  6.]
 [ 8. 10. 12.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]]


# Cvičení

In [36]:
c = np.array([
    range(4),
    range(10, 14),
])
c

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

Napiš funkci split, která matici `c` rozdělí na 2 matice `x` a `y`. Matice `x` bude obsahovat všechny sloupce kromě posledního a bude 2D. Matice `y` bude poslední sloupec a bude 1D.

In [ ]:
def split(c):
    # code here
    return x, y

x, y = split(c)
print(x)
print(y)

In [38]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

# zip
- Python, ne numpy

In [39]:
l1 = ["a", "b", "c"]
l2 = [1, 2, 3]

for row in zip(l1, l2):
    print(row)

for e1, e2 in zip(l1, l2):
    print(e1, e2)
    
for i, (e1, e2) in enumerate(zip(l1, l2)):
    print(i, e1, e2)

('a', 1)
('b', 2)
('c', 3)
a 1
b 2
c 3
0 a 1
1 b 2
2 c 3


In [40]:
zipped = list(zip(l1, l2))
zipped

[('a', 1), ('b', 2), ('c', 3)]

In [41]:
l1, l2 = zip(*zipped)
print(l1)
print(l2)

# What * actually do
l1, l2 = zip(zipped[0], zipped[1], zipped[2])
print(l1)
print(l2)

('a', 'b', 'c')
(1, 2, 3)
('a', 'b', 'c')
(1, 2, 3)


# Sorting

In [42]:
l1 = ["b", "b", "a"]
l2 = [3, 1, 2]

In [43]:
sorted(l1)

['a', 'b', 'b']

In [44]:
sorted(l1, reverse=True)

['b', 'b', 'a']

In [45]:
sorted(zip(l1, l2))

[('a', 2), ('b', 1), ('b', 3)]

In [46]:
sorted(zip(l1, l2), key=lambda x: x[1])

[('b', 1), ('a', 2), ('b', 3)]

# Comperhension

In [47]:
l = [str(i) for i in range(5) if i % 2 == 0]
print(l)

# Same as
l = []
for i in range(5):
    if i % 2 == 0:
        l.append(str(i))
print(l)

['0', '2', '4']
['0', '2', '4']


# Split

In [48]:
"a,b,c".split(",")

['a', 'b', 'c']

# Join

In [49]:
",".join(["a", "b", "c"])

'a,b,c'

# Format

In [50]:
"Text {} {}".format("a", 3)

'Text a 3'

In [51]:
"Text {:03d}".format(3)

'Text 003'